# Generated by Django 6.1.1 on 2026-09-30 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ingles', models.CharField(max_length=150)),
                ('nombre_cientifico', models.CharField(max_length=150, unique=True)),
                ('nombre_espanol', models.CharField(blank=True, max_length=150)),
                ('descripcion', models.TextField()),
                ('nivel_dificultad', models.IntegerField(default=1)),
                ('es_migratoria', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionPartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo_juego', models.CharField(max_length=50)),
                ('cantidad_preguntas', models.IntegerField()),
                ('vidas', models.IntegerField()),
                ('tiempo_por_pregunta', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, upload_to='logros/')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImagenAve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='aves/')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('orden', models.IntegerField(default=1)),
                ('ave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='aves.ave')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Migracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=150)),
                ('temporada_llegada', models.CharField(max_length=100)),
                ('temporada_salida', models.CharField(max_length=100)),
                ('ruta', models.TextField()),
                ('ave', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aves.ave')),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vidas_iniciales', models.IntegerField()),
                ('vidas_finales', models.IntegerField()),
                ('puntos_finales', models.IntegerField(default=0)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aves.configuracionpartida')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField(default=1)),
                ('experiencia', models.IntegerField(default=0)),
                ('puntos_totales', models.IntegerField(default=0)),
                ('partidas_jugadas', models.IntegerField(default=0)),
                ('aves_identificadas', models.IntegerField(default=0)),
                ('aciertos_totales', models.IntegerField(default=0)),
                ('errores_totales', models.IntegerField(default=0)),
                ('mejor_puntuacion', models.IntegerField(default=0)),
                ('tiempo_promedio', models.FloatField(default=0)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PistaAve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('nivel', models.IntegerField(default=1)),
                ('orden', models.IntegerField(default=1)),
                ('ave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pistas', to='aves.ave')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pregunta', models.IntegerField()),
                ('tiempo_limite', models.IntegerField(default=10)),
                ('tiempo_utilizado', models.FloatField(blank=True, null=True)),
                ('respondida', models.BooleanField(default=False)),
                ('ave_correcta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aves.ave')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='aves.partida')),
            ],
        ),
        migrations.CreateModel(
            name='OpcionRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_correcta', models.BooleanField(default=False)),
                ('orden', models.IntegerField()),
                ('ave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones_respuesta', to='aves.ave')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='aves.pregunta')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField(default=0)),
                ('tipo_ranking', models.CharField(max_length=50)),
                ('periodo', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='aves.region')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correcta', models.BooleanField(default=False)),
                ('tiempo_utilizado', models.FloatField()),
                ('uso_ayuda', models.BooleanField(default=False)),
                ('puntos_obtenidos', models.IntegerField(default=0)),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aves.opcionrespuesta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='aves.pregunta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioLogro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_obtenido', models.DateTimeField(auto_now_add=True)),
                ('logro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aves.logro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ColeccionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_identificacion', models.DateTimeField(auto_now_add=True)),
                ('cantidad_identificaciones', models.IntegerField(default=1)),
                ('mejor_tiempo', models.FloatField(default=0)),
                ('ave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores_que_identificaron', to='aves.ave')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coleccion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('usuario', 'ave'), name='ave_identificada_usuario')],
            },
        ),
        migrations.CreateModel(
            name='AyudaUsada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('5050', '50/50'), ('cambiar', 'Cambiar pregunta'), ('respuesta', 'Mostrar respuesta')], max_length=20)),
                ('penalizacion', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ayudas', to='aves.partida')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ayudas', to='aves.pregunta')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('pregunta', 'tipo'), name='una_ayuda_por_tipo')],
            },
        ),
        migrations.CreateModel(
            name='DistribucionAve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribuciones', to='aves.ave')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aves.departamento')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aves', to='aves.region')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ave', 'region', 'departamento'), name='distribucion_unica')],
            },
        ),
    ]
