# Generated by Django 6.1.1 on 2026-09-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aves', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='migracion',
            options={'verbose_name': 'Migración', 'verbose_name_plural': 'Migraciones'},
        ),
        migrations.AlterModelOptions(
            name='perfiljugador',
            options={'verbose_name': 'Perfil jugador', 'verbose_name_plural': 'Perfil jugadores'},
        ),
        migrations.AlterModelOptions(
            name='ranking',
            options={'verbose_name': 'Ranking', 'verbose_name_plural': 'Ranking'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Región', 'verbose_name_plural': 'Regiones'},
        ),
        migrations.AlterModelOptions(
            name='respuestajugador',
            options={'verbose_name': 'Respuesta jugador', 'verbose_name_plural': 'Respuesta jugadores'},
        ),
        migrations.RemoveField(
            model_name='departamento',
            name='region',
        ),
        migrations.AddField(
            model_name='departamento',
            name='regiones',
            field=models.ManyToManyField(related_name='departamentos', to='aves.region'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
