# Generated by Django 6.1.1 on 2026-10-01 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aves', '0002_alter_migracion_options_alter_perfiljugador_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ave',
            name='nivel_dificultad',
        ),
    ]
